Updating Undocumented
Blockception/Minecraft-bedrock-json-schemas pull request #180
Opened 2023-08-08 22:39 UTC by DrinkWater623

Mainly under the Entity Components

- Updated descriptions
- Fixed typos
- Corrected data types
- Added 'default' where needed
- Added missing parameters
- Removed invalid parameters
- Added and/or updated examples

Used information from MS-Learn component pages.  
* *Except for entity_placer.json, added logical title and description to the items-array info for the dispense_on/use_on*

2023-08-11 13:24 UTC, DaanV2 requested changes

2023-08-11 13:24 UTC, DaanV2 commented on source/behavior/entities/format/components/is_stackable.json
> -  }
This one need to stay for now, Microsoft uses it in their own entity:
https://learn.microsoft.com/en-us/minecraft/creator/reference/source/vanillabehaviorpack_snippets/entities/chest_minecart

2023-08-11 13:24 UTC, DaanV2 commented on source/behavior/entities/format/components/shooter.json
> +      "description": "Sound that is played when the shooter shoots a projectile."
I don't see these properties in the documentation for shooter 🤔

2023-08-12 16:36 UTC, DrinkWater623 commented on source/behavior/entities/format/components/is_stackable.json
> -  }
So do I just remove it, or do you?   I am kinda new to this github thing.

2023-08-12 16:38 UTC, DrinkWater623 commented on source/behavior/entities/format/components/shooter.json
> +      "description": "Sound that is played when the shooter shoots a projectile."
I got everything from [Microsoft](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_shooter).  Is this not correct, it is there.  Where are you looking?

2023-08-13 08:44 UTC, DaanV2 commented on source/behavior/entities/format/components/is_stackable.json
> -  }
You removed in your code 🙂, So for this case you need to re-add it to the file 😄

2023-08-13 08:45 UTC, DaanV2 commented on source/behavior/entities/format/components/shooter.json
> +      "description": "Sound that is played when the shooter shoots a projectile."
Sorry right, was looking at the minecraft:shooter for items

2023-08-13 09:09 UTC, DrinkWater623 commented
I deleted all changes for that file.  Well I hope I did it right.

2023-08-13 09:11 UTC, DrinkWater623 commented on source/behavior/entities/format/components/is_stackable.json
> -  }
Okay, I think this is where the reply goes...  I deleted my changes for is_stackable.

2023-08-13 09:12 UTC, DrinkWater623 commented
Getting confused about where comments go... anyways, deleted the is_stackable file from the PR.  I think.

2023-08-14 06:19 UTC, DaanV2 commented on source/behavior/entities/format/components/is_stackable.json
> +  "properties": {}
```suggestion
"properties": {
    "value": {
      "title": "Value",
      "description": "UNDOCUMENTED.",
      "type": "boolean"
    }
  }
```

2023-08-14 06:20 UTC, DaanV2 commented on source/behavior/entities/format/components/is_stackable.json
> +"properties": {
```suggestion
  "properties": {
```

2023-08-14 06:20 UTC, DaanV2 approved these changes

2023-08-14 06:21 UTC, merged