Add missing documentation to behavior components
Blockception/Minecraft-bedrock-json-schemas pull request #30
Opened 2022-06-23 19:52 UTC by ben-dodd-dev

Filled in many missing documentation descriptions from the behaviour components schema. 
- A few descriptions are based on those from www.bedrock.dev or my own testing/experience
- A few values were missing minimum/maximum properties and have been added where necessary

Related to issue #15

2022-06-24 17:46 UTC, DaanV2 commented on source/behavior/entities/format/behaviors/defend_trusted_target.json
> +      "maximum": 1
I need to confirm this fact in mc

2022-06-24 17:52 UTC, DaanV2 requested changes
Looks good and thanks for the hard work ☺️ saw a single line that's needs to be checked, and two things I need to confirm in Minecraft

2022-06-24 17:52 UTC, DaanV2 commented on source/behavior/entities/format/behaviors/harvest_farm_block.json
> +      "description": "The maximum amount of time in seconds that the goal can take before searching again, after failing to find a a harvest block already.",
Check spelling on this one, the ending gets a bit weird

2022-06-24 17:52 UTC, DaanV2 commented on source/behavior/entities/format/components/block_sensor.json
> +      "maximum": 32
I need to check if this is indeed the range

2022-06-28 13:08 UTC, mitgobla commented on source/behavior/entities/format/behaviors/defend_trusted_target.json
> +      "maximum": 1
Of course. I added the min/max as chances are usually a float between 0 and 1

2022-06-28 13:11 UTC, ben-dodd-dev commented on source/behavior/entities/format/behaviors/harvest_farm_block.json
> +      "description": "The maximum amount of time in seconds that the goal can take before searching again, after failing to find a a harvest block already.",
Changed (0807257d7876f396a5c03ae6efa39528aaa173bc)

2022-06-28 19:14 UTC, merged