Updated titles
Blockception/Minecraft-bedrock-json-schemas pull request #67
Opened 2022-07-26 14:09 UTC by ChibiMango

Did a mass check for typos in titles and ids of entity components and behaviors
Additionally, added information for `knockback_resistance` after testing and for `navigation.walk`

2022-07-26 16:46 UTC, DaanV2 requested changes
Looking great! Alot of work, also I noticed I missed more titles then I thought 😅 

Just noticed a small typo, and if you could rebase or resolve the merge conflicts it good to go 🚀

2022-07-26 16:46 UTC, DaanV2 commented on source/behavior/entities/format/behaviors/jump_to_block.json
> +  "title": "Jump To Blokc",
Small typo here 😊

2022-07-26 16:57 UTC, ChibiMango commented
Resolved the conflicts and made a small mistake, but fixed now I believe

2022-07-27 05:45 UTC, DaanV2 approved these changes

2022-07-27 05:45 UTC, merged